apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-04-20T06:44:06Z"
  generation: 1
  labels:
    app: n1
  name: n1
  namespace: n1
  resourceVersion: "128503"
  uid: 9a6bb7d1-de75-4a2c-9c2e-518a65ecfd4c
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: n1
    spec:
      containers:
      - image: lafin716/nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
