apiVersion: v1
kind: Service
metadata:
  labels:
    app: n1
  name: n1
  namespace: n1
spec:
  ports:
  - nodePort: 30833
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  type: NodePort
