apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-20T06:58:13Z"
  labels:
    app: n1
  name: n1
  namespace: n1
  resourceVersion: "130603"
  uid: b9f4c2e6-a47a-4e49-a9a2-c4b237d8042a
spec:
  clusterIP: 10.233.60.150
  clusterIPs:
  - 10.233.60.150
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30833
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
